### PR TITLE
Update utm_no runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update org.kryogenix.utm_no runtime to 46

### CODE REVIEW

**Comment by yakushabb** [comment]
It works on Fedora 40 and GNOME 46

**Comment by ghost** [comment]
@stuartlangridge It works on Fedora 40 and GNOME 46

**Comment by ghost** [comment]
@barthalion I updated the utm_no runtime to 46.

Could you review it.

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
